version: "3.7"

services:      
  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      # - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_ADMIN_PASSWORD}
    networks:
      - stellar-chat
    ports:
      - 5341:80
    volumes:
      - seq_data:/data
  
networks:
  stellar-chat:
    name: stellar-chat-network

volumes:
  seq_data: