version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    #environment:                                    # If you disable authentication then you need to remove username and password from connection string in appsettings.
    # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}     
    ports:
      - 27017:27017
    networks:
      - stellar-chat
    volumes:
      - mongo_data:/data/db
  
  seq:
    image: datalust/seq 
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      # - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_ADMIN_PASSWORD}
    networks:
      - stellar-chat
    ports:
      - 5341:80
    volumes:
      - seq_data:/data
  
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    networks:
      - stellar-chat
    ports:
      - 6333:6333
    volumes:
      - qdrant_data:/data

networks:
  stellar-chat:
    name: stellar-chat-network

volumes:
  seq_data:
  mongo_data:
  qdrant_data: